version: '3'

services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
      - ARKOSE_TOKEN_URL=https://api.capsolver.com/createTask
      - CAPSOLVER_API_KEY=YOUR_CAPSOLVER_API_KEY

  arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
