version: '3'

services:
  app:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
      - AUTHORIZATION=YOUR_AUTHORIZATION
#      - FREE35_BASE_URL=https://chat.openai.com/backend-anon
#      - CHATGPT_BASE_URL=https://chat.openai.com/backend-api
#      - HISTORY_DISABLED=false
#      - PROXY_URL=YOUR_PROXY_URL
