version: '3'

services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    environment:
#      - API_PREFIX=your_prefix
#      - PROXY_URL=your_first_proxy, your_second_proxy
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
    deploy:
      resources:
        limits:
          memory: 1G

  arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
#    environment:
#      - VERSION=2.4.8
#      - HASH=ce2493911f3dfdadca4d3d4a7370a09d
#      - PROXY_URL=your_first_proxy
